name: Check package-lock.json

on:
  pull_request:
  push:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci --prefer-offline --no-audit
      - run: npm run package:check
