# .github/workflows/release-template.yml

name: Release Individual Starter

on:
  push:
    tags:
      - '*-v*.*.*' # Triggers on tags like nextjs-v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse tag to extract template name and version
        id: parse
        run: |
          TAG="${GITHUB_REF##*/}"          # e.g. nextjs-v1.0.0
          TEMPLATE="${TAG%%-v*}"           # -> nextjs
          VERSION="${TAG#*-v}"             # -> 1.0.0
          echo "template=$TEMPLATE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Zip individual starter template
        run: |
          mkdir -p dist
          cd ${{ steps.parse.outputs.template }}
          zip -r ../dist/${{ steps.parse.outputs.template }}-${{ steps.parse.outputs.version }}.zip .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "${{ steps.parse.outputs.template }} v${{ steps.parse.outputs.version }}"
          files: dist/*.zip